name: Update latest articles

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute code
        run: php ./curl.php

      - name: Commit and push
        run: |
          git add -N .
          if ! git diff --exit-code --quiet; then
            git config --local user.name 'GitHub Action'
            git config --local user.email 'action@github.com'
            git add README.md
            git commit --message 'Update README.md automatically'
            git push
          fi
