name: Textlint

on:
  pull_request:
    paths:
      - "articles/**.md"
      - "books/**/**.md"
      - "books/**/**.yaml"

jobs:
  textlint:
    name: execute textlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          textlint_flags: "articles/**"
